chore: setup vite and prettier
abemscac/inet-meow0516 pull request #10
Opened 2022-04-25 14:11 UTC by meow0516

Close #1

2022-04-25 14:47 UTC, abemscac commented
讚喔阿姨
我會幫您裝上prettier和eslint，還有一些vscode的設定
您有意願要自己44抗ㄇ
那會是一ㄍ滿痛苦的體驗喔，不強求
畢竟我們練習的重點不在那裡

2022-04-25 14:54 UTC, abemscac commented on .prettierrc.json
> +}
建議再加上兩個設定
- [trailingComma](https://prettier.io/docs/en/options.html#trailing-commas)
  例如：`trailingComma: "es5"`
  設定function arguments/array items/object properties這種東西最後面要不要加逗號。
- [semi](https://prettier.io/docs/en/options.html#trailing-commas)
  例如：`semi: true`
  設定script要不要有結尾分號`;`，要的話什麼時候要放。
  我司是用`semi: false`，都沒分號一開始挺不習慣的，不過久了之後覺得挺讚的。
  看個人喜好，對程式功能沒有影響。

2022-04-25 14:56 UTC, abemscac commented on package.json
> +    "vite": "^2.9.5",
您直接就vite起乃ㄌㄛ
還以為您會選擇用vue-cli的，vite的確是個好選擇，早い

2022-04-25 14:59 UTC, abemscac commented on tsconfig.json
> +  },
建議再加上兩個設定
- [noImplicitAny](https://www.typescriptlang.org/tsconfig#noImplicitAny)
  他會幫我們每個function的參數都有給型別，不會是`any`。
- [strictNullChecks](https://www.typescriptlang.org/tsconfig#strictNullChecks)
  加上去之後`null`和`undefined`就會被認為是不同型別，安全很多。

2022-04-25 15:01 UTC, abemscac commented
@meow0516 如果您覺得prettier和eslint太麻煩的話，那些PR review的小改動可以不改。
可以在我這裡改一改就好，反正我也要加一些東西，我再寫一些說明供您參考。
您要自己挑讚ㄉ話當南也ㄎ以r，威猛re。

2022-04-26 15:36 UTC, meow0516 commented on .prettierrc.json
> +}
所以這個作法是我要在本地branch新增以上內容->commit＆push 到remote branch->再做一次PRㄇ

2022-04-26 22:38 UTC, abemscac commented on .prettierrc.json
> +}
e照reviewㄉ結果做出改動就可以了，不用再建PR
因為PR是跟著branch的，所以您在本地改完->commit&push之後這個PR就會看的到那些改動，又可以再review一次

2022-04-26 22:39 UTC, abemscac commented on .prettierrc.json
> +}
我應該按那個request changes的
抱歉  等等按ㄍ

2022-04-26 22:42 UTC, abemscac requested changes
東c加一加ㄗ後commit&push 9可以ㄌ
等您做完之後我們再看一次，沒問題的話我就加上一些CI的東西
然後我把它rebase&merge回main
#1 的說明之前有更新，有提到git workflow的流程，您有空的時候可以再去抗抗
感謝re

2022-04-27 12:22 UTC, abemscac commented
@meow0516 yo阿姨
1. 您的哈士奇會動了ㄇ
    ☐是  ☐否
2. 您是否想要挑戰設置eslint
    ☐是  ☐否

2022-04-27 14:30 UTC, meow0516 commented
@abemscac 
1. 哈士奇遇到sourcetree還是不能動，但我決定摸摸鼻子乖乖習慣用cmd 操作git
2. 這次先不

2022-04-27 14:51 UTC, abemscac commented
好8  真是太奇怪ㄌ
我是說問題
我想他跟您的sourcetree/裝置設定有一點關係，不過暫時先不理他
我們阿姨cmd一樣用的嚇嚇叫
我明天把eslint和ci的東西裝上去，您就可以繼續往下做了

2022-04-27 23:54 UTC, abemscac commented on .vscode/extensions.json
> +}
加上建議的vscode插件列表
這樣別人用vscode打開這個workspace的時候就會看到他跳訊息出來，建議他安裝這些東西
裡面的值是plugin的id

2022-04-27 23:57 UTC, abemscac commented on .vscode/settings.json
> +}
這是workspace層級的vscode設定
我們可以在vscode的設定裡面把formatOnSave打開，但是那會影響到您的裝置上所有的專案，因為都是用同一個vscode在開東西
有些專案之前沒裝prettier，formatOnSave開下去就會一大堆changes，不太理想
這種workspace層級的設定只會影響到這個資料裡面的檔案，不會影響到其他workspace/repository

2022-04-27 23:58 UTC, abemscac commented on package.json
> +    "eslint-plugin-vue": "^8.7.1",
eslint的東c

2022-04-28 00:03 UTC, abemscac commented on .github/workflows/pr-commit.yaml
> +name: PR Commit
這ㄍ東c4給[Github Actions](https://docs.github.com/en/actions)用的，不知道您是否已經聽過了
他可以在某些事情發生的時候幫我們做一些事情
例如說這個action，我們的設定就是「當有想要merge到main的PR發生的時候，就幫我們執行prettier和eslint的檢查」
所以您現在在PR旁邊都會看到一個綠色勾勾或是紅色叉叉
<img width="440" alt="image" src="https://user-images.githubusercontent.com/59676941/165650185-8f5ef035-80d5-413b-a3c4-c56bf8b83930.png">

PR詳細資訊下面也有
<img width="704" alt="image" src="https://user-images.githubusercontent.com/59676941/165650229-19c5501b-6bcf-46df-9db6-7708435ab075.png">

這是用來維持程式碼品質的一個好工具，可以把那些__code在進入main之前通通抓出來

2022-04-28 00:04 UTC, abemscac approved these changes

2022-04-28 00:04 UTC, merged

2022-04-28 00:06 UTC, abemscac commented
@meow0516 yo阿姨
這個PR已經通過review+合併回main了，一個循環就做完了
Github workflow就是一直重複領issue -> 開發 -> PR -> review -> 合併回main這個流程
您已經往前邁進一大步ㄌ  恭喜阿姨